// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/config.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import framework "github.com/maxhawkins/tensorflow-serving-go/tensorflow/core/framework"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Optimization level
type OptimizerOptions_Level int32

const (
	// L1 is the default level.
	// Optimization performed at L1 :
	// 1. Common subexpression elimination
	// 2. Constant folding
	OptimizerOptions_L1 OptimizerOptions_Level = 0
	// No optimizations
	OptimizerOptions_L0 OptimizerOptions_Level = -1
)

var OptimizerOptions_Level_name = map[int32]string{
	0:  "L1",
	-1: "L0",
}
var OptimizerOptions_Level_value = map[string]int32{
	"L1": 0,
	"L0": -1,
}

func (x OptimizerOptions_Level) String() string {
	return proto.EnumName(OptimizerOptions_Level_name, int32(x))
}
func (OptimizerOptions_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{1, 0}
}

// Control the use of the compiler/jit.  Experimental.
type OptimizerOptions_GlobalJitLevel int32

const (
	OptimizerOptions_DEFAULT OptimizerOptions_GlobalJitLevel = 0
	OptimizerOptions_OFF     OptimizerOptions_GlobalJitLevel = -1
	// The following settings turn on compilation, with higher values being
	// more aggressive.  Higher values may reduce opportunities for parallelism
	// and may use more memory.  (At present, there is no distinction, but this
	// is expected to change.)
	OptimizerOptions_ON_1 OptimizerOptions_GlobalJitLevel = 1
	OptimizerOptions_ON_2 OptimizerOptions_GlobalJitLevel = 2
)

var OptimizerOptions_GlobalJitLevel_name = map[int32]string{
	0:  "DEFAULT",
	-1: "OFF",
	1:  "ON_1",
	2:  "ON_2",
}
var OptimizerOptions_GlobalJitLevel_value = map[string]int32{
	"DEFAULT": 0,
	"OFF":     -1,
	"ON_1":    1,
	"ON_2":    2,
}

func (x OptimizerOptions_GlobalJitLevel) String() string {
	return proto.EnumName(OptimizerOptions_GlobalJitLevel_name, int32(x))
}
func (OptimizerOptions_GlobalJitLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{1, 1}
}

// TODO(pbar) Turn this into a TraceOptions proto which allows
// tracing to be controlled in a more orthogonal manner?
type RunOptions_TraceLevel int32

const (
	RunOptions_NO_TRACE       RunOptions_TraceLevel = 0
	RunOptions_SOFTWARE_TRACE RunOptions_TraceLevel = 1
	RunOptions_HARDWARE_TRACE RunOptions_TraceLevel = 2
	RunOptions_FULL_TRACE     RunOptions_TraceLevel = 3
)

var RunOptions_TraceLevel_name = map[int32]string{
	0: "NO_TRACE",
	1: "SOFTWARE_TRACE",
	2: "HARDWARE_TRACE",
	3: "FULL_TRACE",
}
var RunOptions_TraceLevel_value = map[string]int32{
	"NO_TRACE":       0,
	"SOFTWARE_TRACE": 1,
	"HARDWARE_TRACE": 2,
	"FULL_TRACE":     3,
}

func (x RunOptions_TraceLevel) String() string {
	return proto.EnumName(RunOptions_TraceLevel_name, int32(x))
}
func (RunOptions_TraceLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{6, 0}
}

type GPUOptions struct {
	// Fraction of the available GPU memory to allocate for each process.
	// 1 means to allocate all of the GPU memory, 0.5 means the process
	// allocates up to ~50% of the available GPU memory.
	//
	// GPU memory is pre-allocated unless the allow_growth option is enabled.
	//
	// If greater than 1.0, uses CUDA unified memory to potentially oversubscribe
	// the amount of memory available on the GPU device by using host memory as a
	// swap space. Accessing memory not available on the device will be
	// significantly slower as that would require memory transfer between the host
	// and the device. Options to reduce the memory requirement should be
	// considered before enabling this option as this may come with a negative
	// performance impact. Oversubscription using the unified memory requires
	// Pascal class or newer GPUs and it is currently only supported on the Linux
	// operating system. See
	// https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-requirements
	// for the detailed requirements.
	PerProcessGpuMemoryFraction float64 `protobuf:"fixed64,1,opt,name=per_process_gpu_memory_fraction,json=perProcessGpuMemoryFraction,proto3" json:"per_process_gpu_memory_fraction,omitempty"`
	// If true, the allocator does not pre-allocate the entire specified
	// GPU memory region, instead starting small and growing as needed.
	AllowGrowth bool `protobuf:"varint,4,opt,name=allow_growth,json=allowGrowth,proto3" json:"allow_growth,omitempty"`
	// The type of GPU allocation strategy to use.
	//
	// Allowed values:
	// "": The empty string (default) uses a system-chosen default
	//     which may change over time.
	//
	// "BFC": A "Best-fit with coalescing" algorithm, simplified from a
	//        version of dlmalloc.
	AllocatorType string `protobuf:"bytes,2,opt,name=allocator_type,json=allocatorType,proto3" json:"allocator_type,omitempty"`
	// Delay deletion of up to this many bytes to reduce the number of
	// interactions with gpu driver code.  If 0, the system chooses
	// a reasonable default (several MBs).
	DeferredDeletionBytes int64 `protobuf:"varint,3,opt,name=deferred_deletion_bytes,json=deferredDeletionBytes,proto3" json:"deferred_deletion_bytes,omitempty"`
	// A comma-separated list of GPU ids that determines the 'visible'
	// to 'virtual' mapping of GPU devices.  For example, if TensorFlow
	// can see 8 GPU devices in the process, and one wanted to map
	// visible GPU devices 5 and 3 as "/device:GPU:0", and "/device:GPU:1",
	// then one would specify this field as "5,3".  This field is similar in
	// spirit to the CUDA_VISIBLE_DEVICES environment variable, except
	// it applies to the visible GPU devices in the process.
	//
	// NOTE:
	// 1. The GPU driver provides the process with the visible GPUs
	//    in an order which is not guaranteed to have any correlation to
	//    the *physical* GPU id in the machine.  This field is used for
	//    remapping "visible" to "virtual", which means this operates only
	//    after the process starts.  Users are required to use vendor
	//    specific mechanisms (e.g., CUDA_VISIBLE_DEVICES) to control the
	//    physical to visible device mapping prior to invoking TensorFlow.
	// 2. In the code, the ids in this list are also called "platform GPU id"s,
	//    and the 'virtual' ids of GPU devices (i.e. the ids in the device
	//    name "/device:GPU:<id>") are also called "TF GPU id"s. Please
	//    refer to third_party/tensorflow/core/common_runtime/gpu/gpu_id.h
	//    for more information.
	VisibleDeviceList string `protobuf:"bytes,5,opt,name=visible_device_list,json=visibleDeviceList,proto3" json:"visible_device_list,omitempty"`
	// In the event polling loop sleep this many microseconds between
	// PollEvents calls, when the queue is not empty.  If value is not
	// set or set to 0, gets set to a non-zero default.
	PollingActiveDelayUsecs int32 `protobuf:"varint,6,opt,name=polling_active_delay_usecs,json=pollingActiveDelayUsecs,proto3" json:"polling_active_delay_usecs,omitempty"`
	// This field is deprecated and ignored.
	PollingInactiveDelayMsecs int32 `protobuf:"varint,7,opt,name=polling_inactive_delay_msecs,json=pollingInactiveDelayMsecs,proto3" json:"polling_inactive_delay_msecs,omitempty"`
	// Force all tensors to be gpu_compatible. On a GPU-enabled TensorFlow,
	// enabling this option forces all CPU tensors to be allocated with Cuda
	// pinned memory. Normally, TensorFlow will infer which tensors should be
	// allocated as the pinned memory. But in case where the inference is
	// incomplete, this option can significantly speed up the cross-device memory
	// copy performance as long as it fits the memory.
	// Note that this option is not something that should be
	// enabled by default for unknown or very large models, since all Cuda pinned
	// memory is unpageable, having too much pinned memory might negatively impact
	// the overall host system performance.
	ForceGpuCompatible bool `protobuf:"varint,8,opt,name=force_gpu_compatible,json=forceGpuCompatible,proto3" json:"force_gpu_compatible,omitempty"`
	// Everything inside experimental is subject to change and is not subject
	// to API stability guarantees in
	// https://www.tensorflow.org/guide/version_compat.
	Experimental         *GPUOptions_Experimental `protobuf:"bytes,9,opt,name=experimental,proto3" json:"experimental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GPUOptions) Reset()         { *m = GPUOptions{} }
func (m *GPUOptions) String() string { return proto.CompactTextString(m) }
func (*GPUOptions) ProtoMessage()    {}
func (*GPUOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{0}
}
func (m *GPUOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUOptions.Unmarshal(m, b)
}
func (m *GPUOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUOptions.Marshal(b, m, deterministic)
}
func (dst *GPUOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUOptions.Merge(dst, src)
}
func (m *GPUOptions) XXX_Size() int {
	return xxx_messageInfo_GPUOptions.Size(m)
}
func (m *GPUOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GPUOptions proto.InternalMessageInfo

func (m *GPUOptions) GetPerProcessGpuMemoryFraction() float64 {
	if m != nil {
		return m.PerProcessGpuMemoryFraction
	}
	return 0
}

func (m *GPUOptions) GetAllowGrowth() bool {
	if m != nil {
		return m.AllowGrowth
	}
	return false
}

func (m *GPUOptions) GetAllocatorType() string {
	if m != nil {
		return m.AllocatorType
	}
	return ""
}

func (m *GPUOptions) GetDeferredDeletionBytes() int64 {
	if m != nil {
		return m.DeferredDeletionBytes
	}
	return 0
}

func (m *GPUOptions) GetVisibleDeviceList() string {
	if m != nil {
		return m.VisibleDeviceList
	}
	return ""
}

func (m *GPUOptions) GetPollingActiveDelayUsecs() int32 {
	if m != nil {
		return m.PollingActiveDelayUsecs
	}
	return 0
}

func (m *GPUOptions) GetPollingInactiveDelayMsecs() int32 {
	if m != nil {
		return m.PollingInactiveDelayMsecs
	}
	return 0
}

func (m *GPUOptions) GetForceGpuCompatible() bool {
	if m != nil {
		return m.ForceGpuCompatible
	}
	return false
}

func (m *GPUOptions) GetExperimental() *GPUOptions_Experimental {
	if m != nil {
		return m.Experimental
	}
	return nil
}

type GPUOptions_Experimental struct {
	// The multi virtual device settings. If empty (not set), it will create
	// single virtual device on each visible GPU, according to the settings
	// in "visible_device_list" above. Otherwise, the number of elements in the
	// list must be the same as the number of visible GPUs (after
	// "visible_device_list" filtering if it is set), and the string represented
	// device names (e.g. /device:GPU:<id>) will refer to the virtual
	// devices and have the <id> field assigned sequentially starting from 0,
	// according to the order they appear in this list and the "memory_limit"
	// list inside each element. For example,
	//   visible_device_list = "1,0"
	//   virtual_devices { memory_limit: 1GB memory_limit: 2GB }
	//   virtual_devices {}
	// will create three virtual devices as:
	//   /device:GPU:0 -> visible GPU 1 with 1GB memory
	//   /device:GPU:1 -> visible GPU 1 with 2GB memory
	//   /device:GPU:2 -> visible GPU 0 with all available memory
	//
	// NOTE:
	// 1. It's invalid to set both this and "per_process_gpu_memory_fraction"
	//    at the same time.
	// 2. Currently this setting is per-process, not per-session. Using
	//    different settings in different sessions within same process will
	//    result in undefined behavior.
	VirtualDevices []*GPUOptions_Experimental_VirtualDevices `protobuf:"bytes,1,rep,name=virtual_devices,json=virtualDevices,proto3" json:"virtual_devices,omitempty"`
	// If true, uses CUDA unified memory for memory allocations. If
	// per_process_gpu_memory_fraction option is greater than 1.0, then unified
	// memory is used regardless of the value for this field. See comments for
	// per_process_gpu_memory_fraction field for more details and requirements
	// of the unified memory. This option is useful to oversubscribe memory if
	// multiple processes are sharing a single GPU while individually using less
	// than 1.0 per process memory fraction.
	UseUnifiedMemory bool `protobuf:"varint,2,opt,name=use_unified_memory,json=useUnifiedMemory,proto3" json:"use_unified_memory,omitempty"`
	// If > 1, the number of device-to-device copy streams to create
	// for each GPUDevice.  Default value is 0, which is automatically
	// converted to 1.
	NumDevToDevCopyStreams int32 `protobuf:"varint,3,opt,name=num_dev_to_dev_copy_streams,json=numDevToDevCopyStreams,proto3" json:"num_dev_to_dev_copy_streams,omitempty"`
	// If non-empty, defines a good GPU ring order on a single worker based on
	// device interconnect.  This assumes that all workers have the same GPU
	// topology.  Specify as a comma-separated string, e.g. "3,2,1,0,7,6,5,4".
	// This ring order is used by the RingReducer implementation of
	// CollectiveReduce, and serves as an override to automatic ring order
	// generation in OrderTaskDeviceMap() during CollectiveParam resolution.
	CollectiveRingOrder  string   `protobuf:"bytes,4,opt,name=collective_ring_order,json=collectiveRingOrder,proto3" json:"collective_ring_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPUOptions_Experimental) Reset()         { *m = GPUOptions_Experimental{} }
func (m *GPUOptions_Experimental) String() string { return proto.CompactTextString(m) }
func (*GPUOptions_Experimental) ProtoMessage()    {}
func (*GPUOptions_Experimental) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{0, 0}
}
func (m *GPUOptions_Experimental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUOptions_Experimental.Unmarshal(m, b)
}
func (m *GPUOptions_Experimental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUOptions_Experimental.Marshal(b, m, deterministic)
}
func (dst *GPUOptions_Experimental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUOptions_Experimental.Merge(dst, src)
}
func (m *GPUOptions_Experimental) XXX_Size() int {
	return xxx_messageInfo_GPUOptions_Experimental.Size(m)
}
func (m *GPUOptions_Experimental) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUOptions_Experimental.DiscardUnknown(m)
}

var xxx_messageInfo_GPUOptions_Experimental proto.InternalMessageInfo

func (m *GPUOptions_Experimental) GetVirtualDevices() []*GPUOptions_Experimental_VirtualDevices {
	if m != nil {
		return m.VirtualDevices
	}
	return nil
}

func (m *GPUOptions_Experimental) GetUseUnifiedMemory() bool {
	if m != nil {
		return m.UseUnifiedMemory
	}
	return false
}

func (m *GPUOptions_Experimental) GetNumDevToDevCopyStreams() int32 {
	if m != nil {
		return m.NumDevToDevCopyStreams
	}
	return 0
}

func (m *GPUOptions_Experimental) GetCollectiveRingOrder() string {
	if m != nil {
		return m.CollectiveRingOrder
	}
	return ""
}

// Configuration for breaking down a visible GPU into multiple "virtual"
// devices.
type GPUOptions_Experimental_VirtualDevices struct {
	// Per "virtual" device memory limit, in MB. The number of elements in
	// the list is the number of virtual devices to create on the
	// corresponding visible GPU (see "virtual_devices" below).
	// If empty, it will create single virtual device taking all available
	// memory from the device.
	//
	// For the concept of "visible" and "virtual" GPU, see the comments for
	// "visible_device_list" above for more information.
	MemoryLimitMb        []float32 `protobuf:"fixed32,1,rep,packed,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GPUOptions_Experimental_VirtualDevices) Reset() {
	*m = GPUOptions_Experimental_VirtualDevices{}
}
func (m *GPUOptions_Experimental_VirtualDevices) String() string { return proto.CompactTextString(m) }
func (*GPUOptions_Experimental_VirtualDevices) ProtoMessage()    {}
func (*GPUOptions_Experimental_VirtualDevices) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{0, 0, 0}
}
func (m *GPUOptions_Experimental_VirtualDevices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUOptions_Experimental_VirtualDevices.Unmarshal(m, b)
}
func (m *GPUOptions_Experimental_VirtualDevices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUOptions_Experimental_VirtualDevices.Marshal(b, m, deterministic)
}
func (dst *GPUOptions_Experimental_VirtualDevices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUOptions_Experimental_VirtualDevices.Merge(dst, src)
}
func (m *GPUOptions_Experimental_VirtualDevices) XXX_Size() int {
	return xxx_messageInfo_GPUOptions_Experimental_VirtualDevices.Size(m)
}
func (m *GPUOptions_Experimental_VirtualDevices) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUOptions_Experimental_VirtualDevices.DiscardUnknown(m)
}

var xxx_messageInfo_GPUOptions_Experimental_VirtualDevices proto.InternalMessageInfo

func (m *GPUOptions_Experimental_VirtualDevices) GetMemoryLimitMb() []float32 {
	if m != nil {
		return m.MemoryLimitMb
	}
	return nil
}

// Options passed to the graph optimizer
type OptimizerOptions struct {
	// If true, optimize the graph using common subexpression elimination.
	DoCommonSubexpressionElimination bool `protobuf:"varint,1,opt,name=do_common_subexpression_elimination,json=doCommonSubexpressionElimination,proto3" json:"do_common_subexpression_elimination,omitempty"`
	// If true, perform constant folding optimization on the graph.
	DoConstantFolding bool `protobuf:"varint,2,opt,name=do_constant_folding,json=doConstantFolding,proto3" json:"do_constant_folding,omitempty"`
	// Constant folding optimization replaces tensors whose values can be
	// predetermined, with constant nodes. To avoid inserting too large constants,
	// the size of each constant created can be limited. If this value is zero, a
	// default limit of 10 MiB will be applied. If constant folding optimization
	// is disabled, this value is ignored.
	MaxFoldedConstantInBytes int64 `protobuf:"varint,6,opt,name=max_folded_constant_in_bytes,json=maxFoldedConstantInBytes,proto3" json:"max_folded_constant_in_bytes,omitempty"`
	// If true, perform function inlining on the graph.
	DoFunctionInlining bool `protobuf:"varint,4,opt,name=do_function_inlining,json=doFunctionInlining,proto3" json:"do_function_inlining,omitempty"`
	// Overall optimization level. The actual optimizations applied will be the
	// logical OR of the flags that this level implies and any flags already set.
	OptLevel             OptimizerOptions_Level          `protobuf:"varint,3,opt,name=opt_level,json=optLevel,proto3,enum=tensorflow.OptimizerOptions_Level" json:"opt_level,omitempty"`
	GlobalJitLevel       OptimizerOptions_GlobalJitLevel `protobuf:"varint,5,opt,name=global_jit_level,json=globalJitLevel,proto3,enum=tensorflow.OptimizerOptions_GlobalJitLevel" json:"global_jit_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *OptimizerOptions) Reset()         { *m = OptimizerOptions{} }
func (m *OptimizerOptions) String() string { return proto.CompactTextString(m) }
func (*OptimizerOptions) ProtoMessage()    {}
func (*OptimizerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{1}
}
func (m *OptimizerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimizerOptions.Unmarshal(m, b)
}
func (m *OptimizerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimizerOptions.Marshal(b, m, deterministic)
}
func (dst *OptimizerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimizerOptions.Merge(dst, src)
}
func (m *OptimizerOptions) XXX_Size() int {
	return xxx_messageInfo_OptimizerOptions.Size(m)
}
func (m *OptimizerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimizerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OptimizerOptions proto.InternalMessageInfo

func (m *OptimizerOptions) GetDoCommonSubexpressionElimination() bool {
	if m != nil {
		return m.DoCommonSubexpressionElimination
	}
	return false
}

func (m *OptimizerOptions) GetDoConstantFolding() bool {
	if m != nil {
		return m.DoConstantFolding
	}
	return false
}

func (m *OptimizerOptions) GetMaxFoldedConstantInBytes() int64 {
	if m != nil {
		return m.MaxFoldedConstantInBytes
	}
	return 0
}

func (m *OptimizerOptions) GetDoFunctionInlining() bool {
	if m != nil {
		return m.DoFunctionInlining
	}
	return false
}

func (m *OptimizerOptions) GetOptLevel() OptimizerOptions_Level {
	if m != nil {
		return m.OptLevel
	}
	return OptimizerOptions_L1
}

func (m *OptimizerOptions) GetGlobalJitLevel() OptimizerOptions_GlobalJitLevel {
	if m != nil {
		return m.GlobalJitLevel
	}
	return OptimizerOptions_DEFAULT
}

type GraphOptions struct {
	// If true, use control flow to schedule the activation of Recv nodes.
	// (Currently ignored.)
	EnableRecvScheduling bool `protobuf:"varint,2,opt,name=enable_recv_scheduling,json=enableRecvScheduling,proto3" json:"enable_recv_scheduling,omitempty"`
	// Options controlling how graph is optimized.
	OptimizerOptions *OptimizerOptions `protobuf:"bytes,3,opt,name=optimizer_options,json=optimizerOptions,proto3" json:"optimizer_options,omitempty"`
	// The number of steps to run before returning a cost model detailing
	// the memory usage and performance of each node of the graph. 0 means
	// no cost model.
	BuildCostModel int64 `protobuf:"varint,4,opt,name=build_cost_model,json=buildCostModel,proto3" json:"build_cost_model,omitempty"`
	// The number of steps to skip before collecting statistics for the
	// cost model.
	BuildCostModelAfter int64 `protobuf:"varint,9,opt,name=build_cost_model_after,json=buildCostModelAfter,proto3" json:"build_cost_model_after,omitempty"`
	// Annotate each Node with Op output shape data, to the extent it can
	// be statically inferred.
	InferShapes bool `protobuf:"varint,5,opt,name=infer_shapes,json=inferShapes,proto3" json:"infer_shapes,omitempty"`
	// Only place the subgraphs that are run, rather than the entire graph.
	//
	// This is useful for interactive graph building, where one might
	// produce graphs that cannot be placed during the debugging
	// process.  In particular, it allows the client to continue work in
	// a session after adding a node to a graph whose placement
	// constraints are unsatisfiable.
	PlacePrunedGraph bool `protobuf:"varint,6,opt,name=place_pruned_graph,json=placePrunedGraph,proto3" json:"place_pruned_graph,omitempty"`
	// If true, transfer float values between processes as bfloat16.
	EnableBfloat16Sendrecv bool `protobuf:"varint,7,opt,name=enable_bfloat16_sendrecv,json=enableBfloat16Sendrecv,proto3" json:"enable_bfloat16_sendrecv,omitempty"`
	// If > 0, record a timeline every this many steps.
	// EXPERIMENTAL: This currently has no effect in MasterSession.
	TimelineStep int32 `protobuf:"varint,8,opt,name=timeline_step,json=timelineStep,proto3" json:"timeline_step,omitempty"`
	// Options that control the type and amount of graph rewriting.
	// Not currently configurable via the public Python API (i.e. there is no API
	// stability guarantee if you import RewriterConfig explicitly).
	RewriteOptions       *RewriterConfig `protobuf:"bytes,10,opt,name=rewrite_options,json=rewriteOptions,proto3" json:"rewrite_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GraphOptions) Reset()         { *m = GraphOptions{} }
func (m *GraphOptions) String() string { return proto.CompactTextString(m) }
func (*GraphOptions) ProtoMessage()    {}
func (*GraphOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{2}
}
func (m *GraphOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphOptions.Unmarshal(m, b)
}
func (m *GraphOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphOptions.Marshal(b, m, deterministic)
}
func (dst *GraphOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphOptions.Merge(dst, src)
}
func (m *GraphOptions) XXX_Size() int {
	return xxx_messageInfo_GraphOptions.Size(m)
}
func (m *GraphOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GraphOptions proto.InternalMessageInfo

func (m *GraphOptions) GetEnableRecvScheduling() bool {
	if m != nil {
		return m.EnableRecvScheduling
	}
	return false
}

func (m *GraphOptions) GetOptimizerOptions() *OptimizerOptions {
	if m != nil {
		return m.OptimizerOptions
	}
	return nil
}

func (m *GraphOptions) GetBuildCostModel() int64 {
	if m != nil {
		return m.BuildCostModel
	}
	return 0
}

func (m *GraphOptions) GetBuildCostModelAfter() int64 {
	if m != nil {
		return m.BuildCostModelAfter
	}
	return 0
}

func (m *GraphOptions) GetInferShapes() bool {
	if m != nil {
		return m.InferShapes
	}
	return false
}

func (m *GraphOptions) GetPlacePrunedGraph() bool {
	if m != nil {
		return m.PlacePrunedGraph
	}
	return false
}

func (m *GraphOptions) GetEnableBfloat16Sendrecv() bool {
	if m != nil {
		return m.EnableBfloat16Sendrecv
	}
	return false
}

func (m *GraphOptions) GetTimelineStep() int32 {
	if m != nil {
		return m.TimelineStep
	}
	return 0
}

func (m *GraphOptions) GetRewriteOptions() *RewriterConfig {
	if m != nil {
		return m.RewriteOptions
	}
	return nil
}

type ThreadPoolOptionProto struct {
	// The number of threads in the pool.
	//
	// 0 means the system picks a value based on where this option proto is used
	// (see the declaration of the specific field for more info).
	NumThreads int32 `protobuf:"varint,1,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	// The global name of the threadpool.
	//
	// If empty, then the threadpool is made and used according to the scope it's
	// in - e.g., for a session threadpool, it is used by that session only.
	//
	// If non-empty, then:
	// - a global threadpool associated with this name is looked
	//   up or created. This allows, for example, sharing one threadpool across
	//   many sessions (e.g., like the default behavior, if
	//   inter_op_parallelism_threads is not configured), but still partitioning
	//   into a large and small pool.
	// - if the threadpool for this global_name already exists, then it is an
	//   error if the existing pool was created using a different num_threads
	//   value as is specified on this call.
	// - threadpools created this way are never garbage collected.
	GlobalName           string   `protobuf:"bytes,2,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadPoolOptionProto) Reset()         { *m = ThreadPoolOptionProto{} }
func (m *ThreadPoolOptionProto) String() string { return proto.CompactTextString(m) }
func (*ThreadPoolOptionProto) ProtoMessage()    {}
func (*ThreadPoolOptionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{3}
}
func (m *ThreadPoolOptionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadPoolOptionProto.Unmarshal(m, b)
}
func (m *ThreadPoolOptionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadPoolOptionProto.Marshal(b, m, deterministic)
}
func (dst *ThreadPoolOptionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadPoolOptionProto.Merge(dst, src)
}
func (m *ThreadPoolOptionProto) XXX_Size() int {
	return xxx_messageInfo_ThreadPoolOptionProto.Size(m)
}
func (m *ThreadPoolOptionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadPoolOptionProto.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadPoolOptionProto proto.InternalMessageInfo

func (m *ThreadPoolOptionProto) GetNumThreads() int32 {
	if m != nil {
		return m.NumThreads
	}
	return 0
}

func (m *ThreadPoolOptionProto) GetGlobalName() string {
	if m != nil {
		return m.GlobalName
	}
	return ""
}

type RPCOptions struct {
	// If true, always use RPC to contact the session target.
	//
	// If false (the default option), TensorFlow may use an optimized
	// transport for client-master communication that avoids the RPC
	// stack. This option is primarily for used testing the RPC stack.
	UseRpcForInprocessMaster bool `protobuf:"varint,1,opt,name=use_rpc_for_inprocess_master,json=useRpcForInprocessMaster,proto3" json:"use_rpc_for_inprocess_master,omitempty"`
	// The compression algorithm to be used. One of "deflate", "gzip".
	CompressionAlgorithm string `protobuf:"bytes,2,opt,name=compression_algorithm,json=compressionAlgorithm,proto3" json:"compression_algorithm,omitempty"`
	// If compression_algorithm is set, the compression level to be used.
	// From 0 (no compression), up to 3.
	CompressionLevel     int32    `protobuf:"varint,3,opt,name=compression_level,json=compressionLevel,proto3" json:"compression_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCOptions) Reset()         { *m = RPCOptions{} }
func (m *RPCOptions) String() string { return proto.CompactTextString(m) }
func (*RPCOptions) ProtoMessage()    {}
func (*RPCOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{4}
}
func (m *RPCOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCOptions.Unmarshal(m, b)
}
func (m *RPCOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCOptions.Marshal(b, m, deterministic)
}
func (dst *RPCOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCOptions.Merge(dst, src)
}
func (m *RPCOptions) XXX_Size() int {
	return xxx_messageInfo_RPCOptions.Size(m)
}
func (m *RPCOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RPCOptions proto.InternalMessageInfo

func (m *RPCOptions) GetUseRpcForInprocessMaster() bool {
	if m != nil {
		return m.UseRpcForInprocessMaster
	}
	return false
}

func (m *RPCOptions) GetCompressionAlgorithm() string {
	if m != nil {
		return m.CompressionAlgorithm
	}
	return ""
}

func (m *RPCOptions) GetCompressionLevel() int32 {
	if m != nil {
		return m.CompressionLevel
	}
	return 0
}

// Session configuration parameters.
// The system picks appropriate values for fields that are not set.
type ConfigProto struct {
	// Map from device type name (e.g., "CPU" or "GPU" ) to maximum
	// number of devices of that type to use.  If a particular device
	// type is not found in the map, the system picks an appropriate
	// number.
	DeviceCount map[string]int32 `protobuf:"bytes,1,rep,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// The execution of an individual op (for some op types) can be
	// parallelized on a pool of intra_op_parallelism_threads.
	// 0 means the system picks an appropriate number.
	IntraOpParallelismThreads int32 `protobuf:"varint,2,opt,name=intra_op_parallelism_threads,json=intraOpParallelismThreads,proto3" json:"intra_op_parallelism_threads,omitempty"`
	// Nodes that perform blocking operations are enqueued on a pool of
	// inter_op_parallelism_threads available in each process.
	//
	// 0 means the system picks an appropriate number.
	//
	// Note that the first Session created in the process sets the
	// number of threads for all future sessions unless use_per_session_threads is
	// true or session_inter_op_thread_pool is configured.
	InterOpParallelismThreads int32 `protobuf:"varint,5,opt,name=inter_op_parallelism_threads,json=interOpParallelismThreads,proto3" json:"inter_op_parallelism_threads,omitempty"`
	// If true, use a new set of threads for this session rather than the global
	// pool of threads. Only supported by direct sessions.
	//
	// If false, use the global threads created by the first session, or the
	// per-session thread pools configured by session_inter_op_thread_pool.
	//
	// This option is deprecated. The same effect can be achieved by setting
	// session_inter_op_thread_pool to have one element, whose num_threads equals
	// inter_op_parallelism_threads.
	UsePerSessionThreads bool `protobuf:"varint,9,opt,name=use_per_session_threads,json=usePerSessionThreads,proto3" json:"use_per_session_threads,omitempty"`
	// This option is experimental - it may be replaced with a different mechanism
	// in the future.
	//
	// Configures session thread pools. If this is configured, then RunOptions for
	// a Run call can select the thread pool to use.
	//
	// The intended use is for when some session invocations need to run in a
	// background pool limited to a small number of threads:
	// - For example, a session may be configured to have one large pool (for
	// regular compute) and one small pool (for periodic, low priority work);
	// using the small pool is currently the mechanism for limiting the inter-op
	// parallelism of the low priority work.  Note that it does not limit the
	// parallelism of work spawned by a single op kernel implementation.
	// - Using this setting is normally not needed in training, but may help some
	// serving use cases.
	// - It is also generally recommended to set the global_name field of this
	// proto, to avoid creating multiple large pools. It is typically better to
	// run the non-low-priority work, even across sessions, in a single large
	// pool.
	SessionInterOpThreadPool []*ThreadPoolOptionProto `protobuf:"bytes,12,rep,name=session_inter_op_thread_pool,json=sessionInterOpThreadPool,proto3" json:"session_inter_op_thread_pool,omitempty"`
	// Assignment of Nodes to Devices is recomputed every placement_period
	// steps until the system warms up (at which point the recomputation
	// typically slows down automatically).
	PlacementPeriod int32 `protobuf:"varint,3,opt,name=placement_period,json=placementPeriod,proto3" json:"placement_period,omitempty"`
	// When any filters are present sessions will ignore all devices which do not
	// match the filters. Each filter can be partially specified, e.g. "/job:ps"
	// "/job:worker/replica:3", etc.
	DeviceFilters []string `protobuf:"bytes,4,rep,name=device_filters,json=deviceFilters,proto3" json:"device_filters,omitempty"`
	// Options that apply to all GPUs.
	GpuOptions *GPUOptions `protobuf:"bytes,6,opt,name=gpu_options,json=gpuOptions,proto3" json:"gpu_options,omitempty"`
	// Whether soft placement is allowed. If allow_soft_placement is true,
	// an op will be placed on CPU if
	//   1. there's no GPU implementation for the OP
	// or
	//   2. no GPU devices are known or registered
	// or
	//   3. need to co-locate with reftype input(s) which are from CPU.
	AllowSoftPlacement bool `protobuf:"varint,7,opt,name=allow_soft_placement,json=allowSoftPlacement,proto3" json:"allow_soft_placement,omitempty"`
	// Whether device placements should be logged.
	LogDevicePlacement bool `protobuf:"varint,8,opt,name=log_device_placement,json=logDevicePlacement,proto3" json:"log_device_placement,omitempty"`
	// Options that apply to all graphs.
	GraphOptions *GraphOptions `protobuf:"bytes,10,opt,name=graph_options,json=graphOptions,proto3" json:"graph_options,omitempty"`
	// Global timeout for all blocking operations in this session.  If non-zero,
	// and not overridden on a per-operation basis, this value will be used as the
	// deadline for all blocking operations.
	OperationTimeoutInMs int64 `protobuf:"varint,11,opt,name=operation_timeout_in_ms,json=operationTimeoutInMs,proto3" json:"operation_timeout_in_ms,omitempty"`
	// Options that apply when this session uses the distributed runtime.
	RpcOptions *RPCOptions `protobuf:"bytes,13,opt,name=rpc_options,json=rpcOptions,proto3" json:"rpc_options,omitempty"`
	// Optional list of all workers to use in this session.
	ClusterDef *ClusterDef `protobuf:"bytes,14,opt,name=cluster_def,json=clusterDef,proto3" json:"cluster_def,omitempty"`
	// If true, any resources such as Variables used in the session will not be
	// shared with other sessions.
	IsolateSessionState  bool                      `protobuf:"varint,15,opt,name=isolate_session_state,json=isolateSessionState,proto3" json:"isolate_session_state,omitempty"`
	Experimental         *ConfigProto_Experimental `protobuf:"bytes,16,opt,name=experimental,proto3" json:"experimental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConfigProto) Reset()         { *m = ConfigProto{} }
func (m *ConfigProto) String() string { return proto.CompactTextString(m) }
func (*ConfigProto) ProtoMessage()    {}
func (*ConfigProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{5}
}
func (m *ConfigProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigProto.Unmarshal(m, b)
}
func (m *ConfigProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigProto.Marshal(b, m, deterministic)
}
func (dst *ConfigProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigProto.Merge(dst, src)
}
func (m *ConfigProto) XXX_Size() int {
	return xxx_messageInfo_ConfigProto.Size(m)
}
func (m *ConfigProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigProto proto.InternalMessageInfo

func (m *ConfigProto) GetDeviceCount() map[string]int32 {
	if m != nil {
		return m.DeviceCount
	}
	return nil
}

func (m *ConfigProto) GetIntraOpParallelismThreads() int32 {
	if m != nil {
		return m.IntraOpParallelismThreads
	}
	return 0
}

func (m *ConfigProto) GetInterOpParallelismThreads() int32 {
	if m != nil {
		return m.InterOpParallelismThreads
	}
	return 0
}

func (m *ConfigProto) GetUsePerSessionThreads() bool {
	if m != nil {
		return m.UsePerSessionThreads
	}
	return false
}

func (m *ConfigProto) GetSessionInterOpThreadPool() []*ThreadPoolOptionProto {
	if m != nil {
		return m.SessionInterOpThreadPool
	}
	return nil
}

func (m *ConfigProto) GetPlacementPeriod() int32 {
	if m != nil {
		return m.PlacementPeriod
	}
	return 0
}

func (m *ConfigProto) GetDeviceFilters() []string {
	if m != nil {
		return m.DeviceFilters
	}
	return nil
}

func (m *ConfigProto) GetGpuOptions() *GPUOptions {
	if m != nil {
		return m.GpuOptions
	}
	return nil
}

func (m *ConfigProto) GetAllowSoftPlacement() bool {
	if m != nil {
		return m.AllowSoftPlacement
	}
	return false
}

func (m *ConfigProto) GetLogDevicePlacement() bool {
	if m != nil {
		return m.LogDevicePlacement
	}
	return false
}

func (m *ConfigProto) GetGraphOptions() *GraphOptions {
	if m != nil {
		return m.GraphOptions
	}
	return nil
}

func (m *ConfigProto) GetOperationTimeoutInMs() int64 {
	if m != nil {
		return m.OperationTimeoutInMs
	}
	return 0
}

func (m *ConfigProto) GetRpcOptions() *RPCOptions {
	if m != nil {
		return m.RpcOptions
	}
	return nil
}

func (m *ConfigProto) GetClusterDef() *ClusterDef {
	if m != nil {
		return m.ClusterDef
	}
	return nil
}

func (m *ConfigProto) GetIsolateSessionState() bool {
	if m != nil {
		return m.IsolateSessionState
	}
	return false
}

func (m *ConfigProto) GetExperimental() *ConfigProto_Experimental {
	if m != nil {
		return m.Experimental
	}
	return nil
}

// Everything inside Experimental is subject to change and is not subject
// to API stability guarantees in
// https://www.tensorflow.org/guide/version_compat.
type ConfigProto_Experimental struct {
	// Task name for group resolution.
	CollectiveGroupLeader string `protobuf:"bytes,1,opt,name=collective_group_leader,json=collectiveGroupLeader,proto3" json:"collective_group_leader,omitempty"`
	// Which executor to use, the default executor will be used
	// if it is an empty string or "DEFAULT"
	ExecutorType string `protobuf:"bytes,3,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"`
	// Guidance to formatting of large RecvBuf fields for transfer.
	// Any positive value sets the max chunk size.  0 defaults to 4096.
	// Any negative value indicates no max, i.e. one chunk only.
	RecvBufMaxChunk int32 `protobuf:"varint,4,opt,name=recv_buf_max_chunk,json=recvBufMaxChunk,proto3" json:"recv_buf_max_chunk,omitempty"`
	// If true, and supported by the platform, the runtime will attempt to
	// use NUMA affinity where applicable.  One consequence will be the
	// existence of as many CPU devices as there are available NUMA nodes.
	UseNumaAffinity bool `protobuf:"varint,5,opt,name=use_numa_affinity,json=useNumaAffinity,proto3" json:"use_numa_affinity,omitempty"`
	// If true, make collective op execution order sequential and deterministic
	// for potentially concurrent collective instances.
	CollectiveDeterministicSequentialExecution bool     `protobuf:"varint,6,opt,name=collective_deterministic_sequential_execution,json=collectiveDeterministicSequentialExecution,proto3" json:"collective_deterministic_sequential_execution,omitempty"`
	XXX_NoUnkeyedLiteral                       struct{} `json:"-"`
	XXX_unrecognized                           []byte   `json:"-"`
	XXX_sizecache                              int32    `json:"-"`
}

func (m *ConfigProto_Experimental) Reset()         { *m = ConfigProto_Experimental{} }
func (m *ConfigProto_Experimental) String() string { return proto.CompactTextString(m) }
func (*ConfigProto_Experimental) ProtoMessage()    {}
func (*ConfigProto_Experimental) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{5, 1}
}
func (m *ConfigProto_Experimental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigProto_Experimental.Unmarshal(m, b)
}
func (m *ConfigProto_Experimental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigProto_Experimental.Marshal(b, m, deterministic)
}
func (dst *ConfigProto_Experimental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigProto_Experimental.Merge(dst, src)
}
func (m *ConfigProto_Experimental) XXX_Size() int {
	return xxx_messageInfo_ConfigProto_Experimental.Size(m)
}
func (m *ConfigProto_Experimental) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigProto_Experimental.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigProto_Experimental proto.InternalMessageInfo

func (m *ConfigProto_Experimental) GetCollectiveGroupLeader() string {
	if m != nil {
		return m.CollectiveGroupLeader
	}
	return ""
}

func (m *ConfigProto_Experimental) GetExecutorType() string {
	if m != nil {
		return m.ExecutorType
	}
	return ""
}

func (m *ConfigProto_Experimental) GetRecvBufMaxChunk() int32 {
	if m != nil {
		return m.RecvBufMaxChunk
	}
	return 0
}

func (m *ConfigProto_Experimental) GetUseNumaAffinity() bool {
	if m != nil {
		return m.UseNumaAffinity
	}
	return false
}

func (m *ConfigProto_Experimental) GetCollectiveDeterministicSequentialExecution() bool {
	if m != nil {
		return m.CollectiveDeterministicSequentialExecution
	}
	return false
}

// Options for a single Run() call.
type RunOptions struct {
	TraceLevel RunOptions_TraceLevel `protobuf:"varint,1,opt,name=trace_level,json=traceLevel,proto3,enum=tensorflow.RunOptions_TraceLevel" json:"trace_level,omitempty"`
	// Time to wait for operation to complete in milliseconds.
	TimeoutInMs int64 `protobuf:"varint,2,opt,name=timeout_in_ms,json=timeoutInMs,proto3" json:"timeout_in_ms,omitempty"`
	// The thread pool to use, if session_inter_op_thread_pool is configured.
	// To use the caller thread set this to -1 - this uses the caller thread
	// to execute Session::Run() and thus avoids a context switch. Using the
	// caller thread to execute Session::Run() should be done ONLY for simple
	// graphs, where the overhead of an additional context switch is
	// comparable with the overhead of Session::Run().
	InterOpThreadPool int32 `protobuf:"varint,3,opt,name=inter_op_thread_pool,json=interOpThreadPool,proto3" json:"inter_op_thread_pool,omitempty"`
	// Whether the partition graph(s) executed by the executor(s) should be
	// outputted via RunMetadata.
	OutputPartitionGraphs bool `protobuf:"varint,5,opt,name=output_partition_graphs,json=outputPartitionGraphs,proto3" json:"output_partition_graphs,omitempty"`
	// EXPERIMENTAL.  Options used to initialize DebuggerState, if enabled.
	DebugOptions *DebugOptions `protobuf:"bytes,6,opt,name=debug_options,json=debugOptions,proto3" json:"debug_options,omitempty"`
	// When enabled, causes tensor allocation information to be included in
	// the error message when the Run() call fails because the allocator ran
	// out of memory (OOM).
	//
	// Enabling this option can slow down the Run() call.
	ReportTensorAllocationsUponOom bool                     `protobuf:"varint,7,opt,name=report_tensor_allocations_upon_oom,json=reportTensorAllocationsUponOom,proto3" json:"report_tensor_allocations_upon_oom,omitempty"`
	Experimental                   *RunOptions_Experimental `protobuf:"bytes,8,opt,name=experimental,proto3" json:"experimental,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                 `json:"-"`
	XXX_unrecognized               []byte                   `json:"-"`
	XXX_sizecache                  int32                    `json:"-"`
}

func (m *RunOptions) Reset()         { *m = RunOptions{} }
func (m *RunOptions) String() string { return proto.CompactTextString(m) }
func (*RunOptions) ProtoMessage()    {}
func (*RunOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{6}
}
func (m *RunOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunOptions.Unmarshal(m, b)
}
func (m *RunOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunOptions.Marshal(b, m, deterministic)
}
func (dst *RunOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunOptions.Merge(dst, src)
}
func (m *RunOptions) XXX_Size() int {
	return xxx_messageInfo_RunOptions.Size(m)
}
func (m *RunOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RunOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RunOptions proto.InternalMessageInfo

func (m *RunOptions) GetTraceLevel() RunOptions_TraceLevel {
	if m != nil {
		return m.TraceLevel
	}
	return RunOptions_NO_TRACE
}

func (m *RunOptions) GetTimeoutInMs() int64 {
	if m != nil {
		return m.TimeoutInMs
	}
	return 0
}

func (m *RunOptions) GetInterOpThreadPool() int32 {
	if m != nil {
		return m.InterOpThreadPool
	}
	return 0
}

func (m *RunOptions) GetOutputPartitionGraphs() bool {
	if m != nil {
		return m.OutputPartitionGraphs
	}
	return false
}

func (m *RunOptions) GetDebugOptions() *DebugOptions {
	if m != nil {
		return m.DebugOptions
	}
	return nil
}

func (m *RunOptions) GetReportTensorAllocationsUponOom() bool {
	if m != nil {
		return m.ReportTensorAllocationsUponOom
	}
	return false
}

func (m *RunOptions) GetExperimental() *RunOptions_Experimental {
	if m != nil {
		return m.Experimental
	}
	return nil
}

// Everything inside Experimental is subject to change and is not subject
// to API stability guarantees in
// https://www.tensorflow.org/guide/version_compat.
type RunOptions_Experimental struct {
	// If non-zero, declares that this graph is going to use collective
	// ops and must synchronize step_ids with any other graph with this
	// same group_key value (in a distributed computation where tasks
	// run disjoint graphs).
	CollectiveGraphKey int64 `protobuf:"varint,1,opt,name=collective_graph_key,json=collectiveGraphKey,proto3" json:"collective_graph_key,omitempty"`
	// If true, then operations (using the inter-op pool) across all
	// session::run() calls will be centrally scheduled, optimizing for (median
	// and tail) latency.
	// Consider using this option for CPU-bound workloads like inference.
	UseRunHandlerPool    bool     `protobuf:"varint,2,opt,name=use_run_handler_pool,json=useRunHandlerPool,proto3" json:"use_run_handler_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunOptions_Experimental) Reset()         { *m = RunOptions_Experimental{} }
func (m *RunOptions_Experimental) String() string { return proto.CompactTextString(m) }
func (*RunOptions_Experimental) ProtoMessage()    {}
func (*RunOptions_Experimental) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{6, 0}
}
func (m *RunOptions_Experimental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunOptions_Experimental.Unmarshal(m, b)
}
func (m *RunOptions_Experimental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunOptions_Experimental.Marshal(b, m, deterministic)
}
func (dst *RunOptions_Experimental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunOptions_Experimental.Merge(dst, src)
}
func (m *RunOptions_Experimental) XXX_Size() int {
	return xxx_messageInfo_RunOptions_Experimental.Size(m)
}
func (m *RunOptions_Experimental) XXX_DiscardUnknown() {
	xxx_messageInfo_RunOptions_Experimental.DiscardUnknown(m)
}

var xxx_messageInfo_RunOptions_Experimental proto.InternalMessageInfo

func (m *RunOptions_Experimental) GetCollectiveGraphKey() int64 {
	if m != nil {
		return m.CollectiveGraphKey
	}
	return 0
}

func (m *RunOptions_Experimental) GetUseRunHandlerPool() bool {
	if m != nil {
		return m.UseRunHandlerPool
	}
	return false
}

// Metadata output (i.e., non-Tensor) for a single Run() call.
type RunMetadata struct {
	// Statistics traced for this step. Populated if tracing is turned on via the
	// "RunOptions" proto.
	// EXPERIMENTAL: The format and set of events may change in future versions.
	StepStats *framework.StepStats `protobuf:"bytes,1,opt,name=step_stats,json=stepStats,proto3" json:"step_stats,omitempty"`
	// The cost graph for the computation defined by the run call.
	CostGraph *framework.CostGraphDef `protobuf:"bytes,2,opt,name=cost_graph,json=costGraph,proto3" json:"cost_graph,omitempty"`
	// Graphs of the partitions executed by executors.
	PartitionGraphs      []*framework.GraphDef `protobuf:"bytes,3,rep,name=partition_graphs,json=partitionGraphs,proto3" json:"partition_graphs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RunMetadata) Reset()         { *m = RunMetadata{} }
func (m *RunMetadata) String() string { return proto.CompactTextString(m) }
func (*RunMetadata) ProtoMessage()    {}
func (*RunMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{7}
}
func (m *RunMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMetadata.Unmarshal(m, b)
}
func (m *RunMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMetadata.Marshal(b, m, deterministic)
}
func (dst *RunMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMetadata.Merge(dst, src)
}
func (m *RunMetadata) XXX_Size() int {
	return xxx_messageInfo_RunMetadata.Size(m)
}
func (m *RunMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RunMetadata proto.InternalMessageInfo

func (m *RunMetadata) GetStepStats() *framework.StepStats {
	if m != nil {
		return m.StepStats
	}
	return nil
}

func (m *RunMetadata) GetCostGraph() *framework.CostGraphDef {
	if m != nil {
		return m.CostGraph
	}
	return nil
}

func (m *RunMetadata) GetPartitionGraphs() []*framework.GraphDef {
	if m != nil {
		return m.PartitionGraphs
	}
	return nil
}

// Defines a connection between two tensors in a `GraphDef`.
type TensorConnection struct {
	// A tensor name. The value of this tensor will be substituted for
	// the tensor named in `to_tensor`.
	FromTensor string `protobuf:"bytes,1,opt,name=from_tensor,json=fromTensor,proto3" json:"from_tensor,omitempty"`
	// A tensor name. The value of this tensor will be bound to the
	// value of the tensor named in `from_tensor`.
	ToTensor             string   `protobuf:"bytes,2,opt,name=to_tensor,json=toTensor,proto3" json:"to_tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TensorConnection) Reset()         { *m = TensorConnection{} }
func (m *TensorConnection) String() string { return proto.CompactTextString(m) }
func (*TensorConnection) ProtoMessage()    {}
func (*TensorConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{8}
}
func (m *TensorConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorConnection.Unmarshal(m, b)
}
func (m *TensorConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorConnection.Marshal(b, m, deterministic)
}
func (dst *TensorConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorConnection.Merge(dst, src)
}
func (m *TensorConnection) XXX_Size() int {
	return xxx_messageInfo_TensorConnection.Size(m)
}
func (m *TensorConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorConnection.DiscardUnknown(m)
}

var xxx_messageInfo_TensorConnection proto.InternalMessageInfo

func (m *TensorConnection) GetFromTensor() string {
	if m != nil {
		return m.FromTensor
	}
	return ""
}

func (m *TensorConnection) GetToTensor() string {
	if m != nil {
		return m.ToTensor
	}
	return ""
}

// Defines a subgraph in another `GraphDef` as a set of feed points and nodes
// to be fetched or executed.
//
// Compare with the arguments to `Session::Run()`.
type CallableOptions struct {
	// Tensors to be fed in the callable. Each feed is the name of a tensor.
	Feed []string `protobuf:"bytes,1,rep,name=feed,proto3" json:"feed,omitempty"`
	// Fetches. A list of tensor names. The caller of the callable expects a
	// tensor to be returned for each fetch[i] (see RunStepResponse.tensor). The
	// order of specified fetches does not change the execution order.
	Fetch []string `protobuf:"bytes,2,rep,name=fetch,proto3" json:"fetch,omitempty"`
	// Target Nodes. A list of node names. The named nodes will be run by the
	// callable but their outputs will not be returned.
	Target []string `protobuf:"bytes,3,rep,name=target,proto3" json:"target,omitempty"`
	// Options that will be applied to each run.
	RunOptions *RunOptions `protobuf:"bytes,4,opt,name=run_options,json=runOptions,proto3" json:"run_options,omitempty"`
	// Tensors to be connected in the callable. Each TensorConnection denotes
	// a pair of tensors in the graph, between which an edge will be created
	// in the callable.
	TensorConnection []*TensorConnection `protobuf:"bytes,5,rep,name=tensor_connection,json=tensorConnection,proto3" json:"tensor_connection,omitempty"`
	// The Tensor objects fed in the callable and fetched from the callable
	// are expected to be backed by host (CPU) memory by default.
	//
	// The options below allow changing that - feeding tensors backed by
	// device memory, or returning tensors that are backed by device memory.
	//
	// The maps below map the name of a feed/fetch tensor (which appears in
	// 'feed' or 'fetch' fields above), to the fully qualified name of the device
	// owning the memory backing the contents of the tensor.
	//
	// For example, creating a callable with the following options:
	//
	// CallableOptions {
	//   feed: "a:0"
	//   feed: "b:0"
	//
	//   fetch: "x:0"
	//   fetch: "y:0"
	//
	//   feed_devices: {
	//     "a:0": "/job:localhost/replica:0/task:0/device:GPU:0"
	//   }
	//
	//   fetch_devices: {
	//     "y:0": "/job:localhost/replica:0/task:0/device:GPU:0"
	//  }
	// }
	//
	// means that the Callable expects:
	// - The first argument ("a:0") is a Tensor backed by GPU memory.
	// - The second argument ("b:0") is a Tensor backed by host memory.
	// and of its return values:
	// - The first output ("x:0") will be backed by host memory.
	// - The second output ("y:0") will be backed by GPU memory.
	//
	// FEEDS:
	// It is the responsibility of the caller to ensure that the memory of the fed
	// tensors will be correctly initialized and synchronized before it is
	// accessed by operations executed during the call to Session::RunCallable().
	//
	// This is typically ensured by using the TensorFlow memory allocators
	// (Device::GetAllocator()) to create the Tensor to be fed.
	//
	// Alternatively, for CUDA-enabled GPU devices, this typically means that the
	// operation that produced the contents of the tensor has completed, i.e., the
	// CUDA stream has been synchronized (e.g., via cuCtxSynchronize() or
	// cuStreamSynchronize()).
	FeedDevices  map[string]string `protobuf:"bytes,6,rep,name=feed_devices,json=feedDevices,proto3" json:"feed_devices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FetchDevices map[string]string `protobuf:"bytes,7,rep,name=fetch_devices,json=fetchDevices,proto3" json:"fetch_devices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// By default, RunCallable() will synchronize the GPU stream before returning
	// fetched tensors on a GPU device, to ensure that the values in those tensors
	// have been produced. This simplifies interacting with the tensors, but
	// potentially incurs a performance hit.
	//
	// If this options is set to true, the caller is responsible for ensuring
	// that the values in the fetched tensors have been produced before they are
	// used. The caller can do this by invoking `Device::Sync()` on the underlying
	// device(s), or by feeding the tensors back to the same Session using
	// `feed_devices` with the same corresponding device name.
	FetchSkipSync        bool     `protobuf:"varint,8,opt,name=fetch_skip_sync,json=fetchSkipSync,proto3" json:"fetch_skip_sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallableOptions) Reset()         { *m = CallableOptions{} }
func (m *CallableOptions) String() string { return proto.CompactTextString(m) }
func (*CallableOptions) ProtoMessage()    {}
func (*CallableOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_24dc408df3eb3b0d, []int{9}
}
func (m *CallableOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallableOptions.Unmarshal(m, b)
}
func (m *CallableOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallableOptions.Marshal(b, m, deterministic)
}
func (dst *CallableOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallableOptions.Merge(dst, src)
}
func (m *CallableOptions) XXX_Size() int {
	return xxx_messageInfo_CallableOptions.Size(m)
}
func (m *CallableOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CallableOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CallableOptions proto.InternalMessageInfo

func (m *CallableOptions) GetFeed() []string {
	if m != nil {
		return m.Feed
	}
	return nil
}

func (m *CallableOptions) GetFetch() []string {
	if m != nil {
		return m.Fetch
	}
	return nil
}

func (m *CallableOptions) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CallableOptions) GetRunOptions() *RunOptions {
	if m != nil {
		return m.RunOptions
	}
	return nil
}

func (m *CallableOptions) GetTensorConnection() []*TensorConnection {
	if m != nil {
		return m.TensorConnection
	}
	return nil
}

func (m *CallableOptions) GetFeedDevices() map[string]string {
	if m != nil {
		return m.FeedDevices
	}
	return nil
}

func (m *CallableOptions) GetFetchDevices() map[string]string {
	if m != nil {
		return m.FetchDevices
	}
	return nil
}

func (m *CallableOptions) GetFetchSkipSync() bool {
	if m != nil {
		return m.FetchSkipSync
	}
	return false
}

func init() {
	proto.RegisterType((*GPUOptions)(nil), "tensorflow.GPUOptions")
	proto.RegisterType((*GPUOptions_Experimental)(nil), "tensorflow.GPUOptions.Experimental")
	proto.RegisterType((*GPUOptions_Experimental_VirtualDevices)(nil), "tensorflow.GPUOptions.Experimental.VirtualDevices")
	proto.RegisterType((*OptimizerOptions)(nil), "tensorflow.OptimizerOptions")
	proto.RegisterType((*GraphOptions)(nil), "tensorflow.GraphOptions")
	proto.RegisterType((*ThreadPoolOptionProto)(nil), "tensorflow.ThreadPoolOptionProto")
	proto.RegisterType((*RPCOptions)(nil), "tensorflow.RPCOptions")
	proto.RegisterType((*ConfigProto)(nil), "tensorflow.ConfigProto")
	proto.RegisterMapType((map[string]int32)(nil), "tensorflow.ConfigProto.DeviceCountEntry")
	proto.RegisterType((*ConfigProto_Experimental)(nil), "tensorflow.ConfigProto.Experimental")
	proto.RegisterType((*RunOptions)(nil), "tensorflow.RunOptions")
	proto.RegisterType((*RunOptions_Experimental)(nil), "tensorflow.RunOptions.Experimental")
	proto.RegisterType((*RunMetadata)(nil), "tensorflow.RunMetadata")
	proto.RegisterType((*TensorConnection)(nil), "tensorflow.TensorConnection")
	proto.RegisterType((*CallableOptions)(nil), "tensorflow.CallableOptions")
	proto.RegisterMapType((map[string]string)(nil), "tensorflow.CallableOptions.FeedDevicesEntry")
	proto.RegisterMapType((map[string]string)(nil), "tensorflow.CallableOptions.FetchDevicesEntry")
	proto.RegisterEnum("tensorflow.OptimizerOptions_Level", OptimizerOptions_Level_name, OptimizerOptions_Level_value)
	proto.RegisterEnum("tensorflow.OptimizerOptions_GlobalJitLevel", OptimizerOptions_GlobalJitLevel_name, OptimizerOptions_GlobalJitLevel_value)
	proto.RegisterEnum("tensorflow.RunOptions_TraceLevel", RunOptions_TraceLevel_name, RunOptions_TraceLevel_value)
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/config.proto", fileDescriptor_config_24dc408df3eb3b0d)
}

var fileDescriptor_config_24dc408df3eb3b0d = []byte{
	// 2312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x52, 0x23, 0xc7,
	0x15, 0xb6, 0xfe, 0xb0, 0x74, 0x24, 0x40, 0xf4, 0xb2, 0x8b, 0x82, 0xb7, 0x62, 0x2c, 0x7b, 0x5d,
	0xc4, 0x3f, 0xec, 0x1a, 0xdb, 0xeb, 0xad, 0xb8, 0xb2, 0x5b, 0x20, 0x10, 0xcb, 0x1a, 0x16, 0x55,
	0x0b, 0x92, 0x4a, 0xe5, 0xa2, 0x6b, 0x34, 0xd3, 0x23, 0x26, 0x3b, 0xd3, 0x3d, 0xee, 0xee, 0x61,
	0x51, 0x2e, 0xf3, 0x04, 0x79, 0x89, 0x5c, 0x26, 0x2f, 0x90, 0xca, 0x9d, 0x1f, 0x2a, 0x57, 0x49,
	0xaa, 0x7f, 0x46, 0x1a, 0x09, 0x16, 0x27, 0xdc, 0x30, 0x73, 0xbe, 0xef, 0x9c, 0xe9, 0x3e, 0x7d,
	0xfe, 0x5a, 0xf0, 0x48, 0x51, 0x26, 0xb9, 0x08, 0x63, 0xfe, 0xf6, 0xb1, 0xcf, 0x05, 0x7d, 0x9c,
	0x0a, 0xae, 0xf8, 0x28, 0x0b, 0x1f, 0xfb, 0x9c, 0x85, 0xd1, 0x78, 0xc7, 0xbc, 0x23, 0x98, 0xd1,
	0x36, 0x3f, 0x5b, 0x54, 0x09, 0x85, 0x97, 0xd0, 0xb7, 0x5c, 0xbc, 0x79, 0xec, 0x73, 0xa9, 0xc8,
	0x58, 0x78, 0xe9, 0xa5, 0xd5, 0xdb, 0x7c, 0xf4, 0x6e, 0x6e, 0x91, 0x76, 0x87, 0x49, 0xa9, 0x68,
	0x4a, 0xa4, 0xf2, 0x94, 0x74, 0xdc, 0x4f, 0xde, 0xb9, 0xe2, 0x80, 0x8e, 0x32, 0xb7, 0xe0, 0xcd,
	0x4f, 0xdf, 0xbd, 0xaf, 0x38, 0x93, 0x8a, 0x0a, 0xc7, 0xdb, 0x79, 0x27, 0x4f, 0xd0, 0xb7, 0x22,
	0x52, 0x54, 0x90, 0xa2, 0x23, 0xba, 0x3f, 0x2d, 0x01, 0x1c, 0x0d, 0x2e, 0xce, 0x52, 0x15, 0x71,
	0x26, 0xd1, 0x01, 0x7c, 0x98, 0x52, 0x41, 0x52, 0xc1, 0x7d, 0x2a, 0x25, 0x19, 0xa7, 0x19, 0x49,
	0x68, 0xc2, 0xc5, 0x84, 0x84, 0xc2, 0xf3, 0x35, 0xa7, 0x53, 0xda, 0x2a, 0x6d, 0x97, 0xf0, 0x07,
	0x29, 0x15, 0x03, 0xcb, 0x3a, 0x4a, 0xb3, 0x53, 0xc3, 0xe9, 0x3b, 0x0a, 0xfa, 0x08, 0x5a, 0x5e,
	0x1c, 0xf3, 0xb7, 0x64, 0x2c, 0xf8, 0x5b, 0x75, 0xd9, 0xa9, 0x6e, 0x95, 0xb6, 0xeb, 0xb8, 0x69,
	0x64, 0x47, 0x46, 0x84, 0x1e, 0xc1, 0x8a, 0x7e, 0xf5, 0x3d, 0xc5, 0x05, 0x51, 0x93, 0x94, 0x76,
	0xca, 0x5b, 0xa5, 0xed, 0x06, 0x5e, 0x9e, 0x4a, 0xcf, 0x27, 0x29, 0x45, 0x4f, 0x61, 0x23, 0xa0,
	0x21, 0x15, 0x82, 0x06, 0x24, 0xa0, 0x31, 0xd5, 0xe6, 0xc9, 0x68, 0xa2, 0xa8, 0xec, 0x54, 0xb6,
	0x4a, 0xdb, 0x15, 0x7c, 0x3f, 0x87, 0x0f, 0x1c, 0xba, 0xaf, 0x41, 0xb4, 0x03, 0xf7, 0xae, 0x22,
	0x19, 0x8d, 0x62, 0x4a, 0x02, 0x7a, 0x15, 0xf9, 0x94, 0xc4, 0x91, 0x54, 0x9d, 0x9a, 0xf9, 0xc6,
	0x9a, 0x83, 0x0e, 0x0c, 0x72, 0x12, 0x49, 0x85, 0xbe, 0x87, 0xcd, 0x94, 0xc7, 0x71, 0xc4, 0xc6,
	0x44, 0xef, 0xe1, 0x4a, 0xab, 0xc5, 0xde, 0x84, 0x64, 0x92, 0xfa, 0xb2, 0xb3, 0xb4, 0x55, 0xda,
	0xae, 0xe1, 0x0d, 0xc7, 0xd8, 0x33, 0x84, 0x03, 0x8d, 0x5f, 0x68, 0x18, 0xbd, 0x80, 0x87, 0xb9,
	0x72, 0xc4, 0xe6, 0xd4, 0x13, 0xa3, 0xfe, 0xbe, 0x51, 0xff, 0x85, 0xe3, 0x1c, 0x3b, 0x8a, 0x31,
	0x70, 0x6a, 0x0c, 0x3c, 0x81, 0xf5, 0x90, 0x0b, 0x9f, 0x1a, 0x7f, 0xfb, 0x3c, 0x49, 0x3d, 0xa5,
	0xd7, 0xd7, 0xa9, 0x1b, 0xbf, 0x21, 0x83, 0x1d, 0xa5, 0x59, 0x6f, 0x8a, 0xa0, 0x23, 0x68, 0xd1,
	0xeb, 0x94, 0x8a, 0x28, 0xa1, 0x4c, 0x79, 0x71, 0xa7, 0xb1, 0x55, 0xda, 0x6e, 0xee, 0x7e, 0x5c,
	0x38, 0xfd, 0x9d, 0xd9, 0xa9, 0xee, 0x1c, 0x16, 0xa8, 0x78, 0x4e, 0x71, 0xf3, 0xa7, 0x32, 0xb4,
	0x8a, 0x30, 0xfa, 0x03, 0xac, 0x5e, 0x45, 0x42, 0x65, 0x5e, 0xec, 0x3c, 0x27, 0x3b, 0xa5, 0xad,
	0xca, 0x76, 0x73, 0x77, 0xf7, 0x7f, 0x30, 0xbe, 0xf3, 0x5b, 0xab, 0x6a, 0x3d, 0x2b, 0xf1, 0xca,
	0xd5, 0xdc, 0x3b, 0xfa, 0x02, 0x50, 0x26, 0x29, 0xc9, 0x58, 0x14, 0x46, 0x34, 0x70, 0xa1, 0x65,
	0x4e, 0xbe, 0x8e, 0xdb, 0x99, 0xa4, 0x17, 0x16, 0xb0, 0xe1, 0x84, 0xbe, 0x87, 0x0f, 0x58, 0x96,
	0xe8, 0x65, 0x10, 0xc5, 0xcd, 0x3f, 0x9f, 0xa7, 0x13, 0x22, 0x95, 0xa0, 0x5e, 0x62, 0x03, 0xa0,
	0x86, 0x1f, 0xb0, 0x2c, 0x39, 0xa0, 0x57, 0xe7, 0xfc, 0x80, 0x5e, 0xf5, 0x78, 0x3a, 0x19, 0x5a,
	0x14, 0xed, 0xc2, 0x7d, 0x9f, 0xc7, 0x31, 0xb5, 0xc7, 0x21, 0xf4, 0xe1, 0x70, 0x11, 0x50, 0x61,
	0x82, 0xb1, 0x81, 0xef, 0xcd, 0x40, 0x1c, 0xb1, 0xf1, 0x99, 0x86, 0x36, 0x9f, 0xc1, 0xca, 0xfc,
	0x06, 0xd0, 0xa7, 0xb0, 0xea, 0xe2, 0x3f, 0x8e, 0x92, 0x48, 0x91, 0x64, 0x64, 0xbc, 0x51, 0xc6,
	0xcb, 0x56, 0x7c, 0xa2, 0xa5, 0xa7, 0xa3, 0xee, 0x9f, 0xab, 0xd0, 0xd6, 0x0e, 0x49, 0xa2, 0x3f,
	0x51, 0x91, 0x27, 0xd3, 0x29, 0x7c, 0x1c, 0x70, 0x7d, 0x9e, 0x09, 0x67, 0x44, 0x66, 0x23, 0x7a,
	0x9d, 0x0a, 0x2a, 0xa5, 0x0e, 0x61, 0xaa, 0xcd, 0x31, 0x6f, 0x9a, 0x50, 0x75, 0xbc, 0x15, 0xf0,
	0x9e, 0x61, 0x0e, 0x8b, 0xc4, 0xc3, 0x19, 0x4f, 0xc7, 0xb4, 0x31, 0xc7, 0xa4, 0xf2, 0x98, 0x22,
	0x21, 0x8f, 0x83, 0x88, 0x8d, 0x9d, 0xf7, 0xd6, 0xb4, 0xba, 0x45, 0xfa, 0x16, 0x40, 0xcf, 0xe1,
	0x61, 0xe2, 0x5d, 0x1b, 0x1e, 0x0d, 0x66, 0x7a, 0x51, 0x9e, 0x40, 0x4b, 0x26, 0x81, 0x3a, 0x89,
	0x77, 0xdd, 0x37, 0x94, 0x5c, 0xff, 0xd8, 0xe5, 0xd0, 0x13, 0x58, 0x0f, 0x38, 0x09, 0x33, 0x66,
	0x92, 0x9a, 0x44, 0x2c, 0x8e, 0x98, 0xfe, 0xa0, 0xcd, 0x66, 0x14, 0xf0, 0xbe, 0x83, 0x8e, 0x1d,
	0x82, 0x5e, 0x40, 0x83, 0xa7, 0x8a, 0xc4, 0xf4, 0x8a, 0xc6, 0xe6, 0x78, 0x56, 0x76, 0xbb, 0xc5,
	0xa8, 0x59, 0xf4, 0xd0, 0xce, 0x89, 0x66, 0xe2, 0x3a, 0x4f, 0x95, 0x79, 0x42, 0x17, 0xd0, 0x1e,
	0xc7, 0x7c, 0xe4, 0xc5, 0xe4, 0x8f, 0x51, 0x6e, 0xa7, 0x66, 0xec, 0x7c, 0x7e, 0xa7, 0x9d, 0x23,
	0xa3, 0xf4, 0x2a, 0xb2, 0x66, 0xf0, 0xca, 0x78, 0xee, 0xbd, 0xbb, 0x05, 0x35, 0x6b, 0x7f, 0x09,
	0xca, 0x27, 0x5f, 0xb5, 0xdf, 0x43, 0xab, 0x50, 0x3e, 0x79, 0xd2, 0xfe, 0x4f, 0xfe, 0x57, 0xea,
	0xf6, 0x60, 0x65, 0xde, 0x06, 0x6a, 0xc2, 0xfb, 0x07, 0x87, 0xfd, 0xbd, 0x8b, 0x93, 0xf3, 0xf6,
	0x7b, 0xa8, 0x0d, 0x95, 0xb3, 0x7e, 0xbf, 0xa0, 0x80, 0xea, 0x50, 0x3d, 0x7b, 0x4d, 0xbe, 0x6a,
	0xe7, 0x4f, 0xbb, 0xed, 0x72, 0xf7, 0x2f, 0x55, 0x68, 0x1d, 0xe9, 0x2e, 0x90, 0x07, 0xc0, 0x37,
	0xf0, 0x80, 0x32, 0x4f, 0x17, 0x21, 0x41, 0xfd, 0x2b, 0x22, 0xfd, 0x4b, 0x1a, 0x64, 0xf1, 0xec,
	0xd0, 0xd6, 0x2d, 0x8a, 0xa9, 0x7f, 0x35, 0x9c, 0x62, 0xe8, 0x18, 0xd6, 0x78, 0xbe, 0x41, 0xc2,
	0xad, 0x29, 0xe3, 0xcd, 0xe6, 0xee, 0xc3, 0xbb, 0xbc, 0x80, 0xdb, 0x7c, 0x31, 0x02, 0xb7, 0xa1,
	0x3d, 0xca, 0xa2, 0x58, 0x9f, 0xbe, 0x54, 0x24, 0xe1, 0x01, 0x8d, 0xcd, 0xf1, 0x55, 0xf0, 0x8a,
	0x91, 0xf7, 0xb8, 0x54, 0xa7, 0x5a, 0x8a, 0xbe, 0x86, 0x07, 0x8b, 0x4c, 0xe2, 0x85, 0x8a, 0x0a,
	0x53, 0x5a, 0x2a, 0xf8, 0xde, 0x3c, 0x7f, 0x4f, 0x43, 0xba, 0xce, 0x47, 0x2c, 0xa4, 0x82, 0xc8,
	0x4b, 0x2f, 0xa5, 0xd2, 0x1c, 0x55, 0x1d, 0x37, 0x8d, 0x6c, 0x68, 0x44, 0x3a, 0xe3, 0xd3, 0xd8,
	0xf3, 0x29, 0x49, 0x45, 0xc6, 0x68, 0x60, 0x9b, 0xa9, 0x09, 0xbd, 0x3a, 0x6e, 0x1b, 0x64, 0x60,
	0x00, 0xe3, 0x37, 0xf4, 0x0c, 0x3a, 0xce, 0x61, 0xa3, 0x30, 0xe6, 0x9e, 0xfa, 0xea, 0x29, 0x91,
	0x94, 0x05, 0xda, 0x7b, 0xa6, 0x8a, 0xd6, 0xb1, 0x73, 0xe8, 0xbe, 0x83, 0x87, 0x0e, 0x45, 0x1f,
	0xc3, 0xb2, 0x8a, 0x12, 0x1a, 0x47, 0x8c, 0x12, 0xdd, 0x62, 0x4d, 0xed, 0xac, 0xe1, 0x56, 0x2e,
	0x1c, 0x2a, 0x9a, 0xa2, 0x1e, 0xac, 0xba, 0x2e, 0x38, 0xf5, 0x2b, 0x18, 0xbf, 0x16, 0xdb, 0xe6,
	0x0e, 0x76, 0x8d, 0xb2, 0x67, 0xfa, 0x24, 0x5e, 0x71, 0x2a, 0xce, 0xa7, 0xaf, 0xaa, 0xf5, 0x52,
	0xbb, 0x8c, 0x1f, 0xc9, 0x37, 0x51, 0xfa, 0xb3, 0xb9, 0xdd, 0xfd, 0x3d, 0xdc, 0x3f, 0xbf, 0x14,
	0xd4, 0x0b, 0x06, 0x9c, 0xc7, 0xd6, 0xc2, 0xc0, 0x0c, 0x20, 0x1f, 0x42, 0x53, 0xd7, 0x36, 0x65,
	0x40, 0x69, 0x6a, 0x40, 0x0d, 0x03, 0xcb, 0x12, 0x4b, 0x97, 0x9a, 0xe0, 0x52, 0x81, 0x79, 0x49,
	0xde, 0x1d, 0xc1, 0x8a, 0x5e, 0x7b, 0x09, 0xed, 0xfe, 0xbd, 0x04, 0x80, 0x07, 0xbd, 0xfc, 0xa8,
	0x9f, 0xc3, 0x43, 0x5d, 0x5a, 0x45, 0xea, 0x93, 0x90, 0x0b, 0x12, 0xb1, 0xbc, 0x87, 0x27, 0x9e,
	0x1e, 0x0f, 0x5c, 0x95, 0xe9, 0x64, 0x92, 0xe2, 0xd4, 0xef, 0x73, 0x71, 0x9c, 0x13, 0x4e, 0x0d,
	0x8e, 0xbe, 0xd6, 0xf5, 0x32, 0x99, 0x6e, 0xc2, 0x8b, 0xc7, 0x5c, 0x44, 0xea, 0x32, 0x71, 0x5f,
	0x5e, 0x2f, 0x80, 0x7b, 0x39, 0x86, 0x3e, 0x87, 0xb5, 0xa2, 0xd2, 0x2c, 0xf1, 0x6b, 0xb8, 0x5d,
	0x00, 0x6c, 0x16, 0xfe, 0x03, 0xa0, 0x69, 0x7d, 0x6a, 0x5d, 0xf0, 0x03, 0xb4, 0x5c, 0x6f, 0xf6,
	0x79, 0xc6, 0x94, 0x6b, 0x33, 0xdb, 0xc5, 0xa3, 0x28, 0xd0, 0x77, 0x6c, 0x49, 0xee, 0x69, 0xea,
	0x21, 0x53, 0x62, 0x82, 0x9b, 0xc1, 0x4c, 0xa2, 0x7b, 0x70, 0xc4, 0x94, 0xf0, 0x08, 0x4f, 0x49,
	0xea, 0x09, 0x2f, 0x8e, 0x69, 0x1c, 0xc9, 0x99, 0x83, 0xcb, 0xb6, 0x07, 0x1b, 0xce, 0x59, 0x3a,
	0x98, 0x31, 0x72, 0x7f, 0x5b, 0x03, 0x26, 0xe3, 0x6e, 0x35, 0x50, 0x9b, 0x1a, 0xd0, 0xe9, 0x75,
	0x8b, 0x81, 0x6f, 0x61, 0x43, 0x1f, 0x80, 0x1e, 0x9f, 0xa4, 0xf3, 0x47, 0xae, 0xdb, 0xb0, 0xd9,
	0x9e, 0x49, 0x3a, 0xa0, 0x62, 0x68, 0xc1, 0x5c, 0xcd, 0x83, 0x87, 0x39, 0x7d, 0xfa, 0x7d, 0xab,
	0x47, 0x52, 0xce, 0xe3, 0x4e, 0xcb, 0x78, 0xe5, 0xa3, 0xa2, 0x57, 0x6e, 0x8d, 0x28, 0xdc, 0x71,
	0x66, 0x8e, 0xed, 0x0a, 0x67, 0x24, 0xf4, 0x2b, 0xb0, 0x99, 0xa6, 0x7b, 0xb4, 0x5e, 0x5f, 0xc4,
	0x03, 0x77, 0x48, 0xab, 0x53, 0xf9, 0xc0, 0x88, 0xf5, 0x58, 0xe6, 0xce, 0x24, 0x8c, 0x62, 0x45,
	0x85, 0xec, 0x54, 0xb7, 0x2a, 0x7a, 0x2c, 0xb3, 0xd2, 0xbe, 0x15, 0xa2, 0xef, 0xa0, 0xa9, 0x47,
	0x95, 0x3c, 0x89, 0x96, 0x4c, 0x12, 0x3d, 0xb8, 0x7d, 0x40, 0xc0, 0x30, 0x4e, 0xb3, 0x3c, 0x4a,
	0x9f, 0xc0, 0xba, 0x9d, 0x0c, 0x25, 0x0f, 0x15, 0x99, 0x7e, 0xdd, 0x25, 0x37, 0x32, 0xd8, 0x90,
	0x87, 0x6a, 0x90, 0x23, 0x5a, 0x23, 0xe6, 0xe3, 0x7c, 0x8a, 0x9b, 0x69, 0xb8, 0xd9, 0x28, 0xe6,
	0x63, 0x1b, 0x18, 0x33, 0x8d, 0xdf, 0xc0, 0xb2, 0xa9, 0x32, 0x0b, 0x39, 0xde, 0x99, 0x5b, 0x5e,
	0xa1, 0x4c, 0xe3, 0xd6, 0xb8, 0x58, 0xb4, 0xbf, 0x85, 0x0d, 0x9e, 0x52, 0x61, 0xf2, 0x97, 0xe8,
	0xf2, 0xc1, 0x33, 0xd3, 0x34, 0x13, 0xd9, 0x69, 0x9a, 0x52, 0xb8, 0x3e, 0x85, 0xcf, 0x2d, 0x7a,
	0xcc, 0x4e, 0x8d, 0x4b, 0x74, 0xee, 0xe5, 0xdf, 0x5c, 0xbe, 0xe9, 0x92, 0x59, 0xb2, 0x62, 0x10,
	0xa9, 0x9f, 0x7f, 0xef, 0x3b, 0x68, 0xba, 0x11, 0x9e, 0x04, 0x34, 0xec, 0xac, 0xdc, 0x54, 0xec,
	0x59, 0xf8, 0x80, 0x86, 0x18, 0xfc, 0xe9, 0xb3, 0x9e, 0x70, 0x22, 0xc9, 0x63, 0x4f, 0xd1, 0x69,
	0xc0, 0xe9, 0x7b, 0x05, 0xed, 0xac, 0x1a, 0xd7, 0xdc, 0x73, 0xa0, 0x8b, 0xb7, 0xa1, 0x86, 0xd0,
	0xcb, 0x85, 0xb9, 0xb1, 0x6d, 0xbe, 0xf6, 0xc9, 0xbb, 0x72, 0xee, 0x8e, 0xc1, 0xf1, 0x39, 0xb4,
	0x17, 0x33, 0x52, 0xb7, 0xc9, 0x37, 0x74, 0x62, 0x4a, 0x4d, 0x03, 0xeb, 0x47, 0xb4, 0x0e, 0xb5,
	0x2b, 0x2f, 0xce, 0xa8, 0xcb, 0x3f, 0xfb, 0xf2, 0xeb, 0xf2, 0xb3, 0xd2, 0xe6, 0xdf, 0x16, 0x07,
	0xcf, 0xa7, 0xb0, 0x51, 0x18, 0xd8, 0xc6, 0x82, 0x67, 0x29, 0x89, 0xa9, 0x17, 0xb8, 0xda, 0xd5,
	0xc0, 0x85, 0x79, 0xee, 0x48, 0xa3, 0x27, 0x06, 0xd4, 0x95, 0x9f, 0x5e, 0x53, 0x3f, 0x9b, 0x5e,
	0x24, 0x2a, 0x86, 0xdd, 0xca, 0x85, 0xe6, 0x1e, 0xf1, 0x39, 0x20, 0xd3, 0x82, 0x47, 0x59, 0x48,
	0xf4, 0x50, 0xe4, 0x5f, 0x66, 0xec, 0x8d, 0x69, 0x85, 0x35, 0xbc, 0xaa, 0x91, 0xfd, 0x2c, 0x3c,
	0xf5, 0xae, 0x7b, 0x5a, 0x8c, 0x3e, 0x83, 0x35, 0x9d, 0xc9, 0x2c, 0x4b, 0x3c, 0xe2, 0x85, 0x61,
	0xc4, 0x22, 0x35, 0x71, 0xbd, 0x6d, 0x35, 0x93, 0xf4, 0x75, 0x96, 0x78, 0x7b, 0x4e, 0x8c, 0x3c,
	0xf8, 0xb2, 0xb0, 0xea, 0x80, 0x2a, 0x2a, 0x92, 0x88, 0x45, 0x52, 0x45, 0x3e, 0x91, 0xf4, 0xc7,
	0x8c, 0x32, 0x15, 0x79, 0x31, 0xb1, 0x8b, 0xd1, 0xd3, 0x9e, 0x6d, 0x7d, 0x9f, 0xcd, 0x94, 0x0e,
	0x8a, 0x3a, 0xc3, 0xa9, 0xca, 0x61, 0xae, 0xf1, 0xaa, 0x5a, 0x2f, 0xb7, 0x2b, 0xdd, 0x7f, 0x57,
	0x01, 0x70, 0xc6, 0xf2, 0xa8, 0xd9, 0x87, 0xa6, 0x12, 0xba, 0xaf, 0xda, 0x9a, 0x5b, 0x32, 0x43,
	0xd2, 0x5c, 0x95, 0x98, 0x91, 0x77, 0xce, 0x35, 0xd3, 0x8e, 0x46, 0xa0, 0xa6, 0xcf, 0xa8, 0x6b,
	0x7b, 0xe6, 0x2c, 0xbe, 0xcb, 0x26, 0xbe, 0x9b, 0xaa, 0x10, 0xd6, 0x8f, 0x61, 0xfd, 0xd6, 0xb2,
	0x64, 0xeb, 0xc7, 0x5a, 0x74, 0xa3, 0xd8, 0x3c, 0x85, 0x0d, 0x9e, 0xa9, 0x34, 0x53, 0xba, 0x8a,
	0xaa, 0xc8, 0x64, 0x91, 0xc9, 0xaf, 0x7c, 0x3c, 0xb8, 0x6f, 0xe1, 0x41, 0x8e, 0x9a, 0x54, 0x94,
	0x3a, 0x6b, 0xcd, 0x7d, 0x77, 0xa1, 0xa8, 0xcc, 0x65, 0xed, 0x81, 0x26, 0x4c, 0xb3, 0x36, 0x28,
	0xbc, 0xa1, 0x57, 0xd0, 0x15, 0x34, 0xe5, 0x42, 0x11, 0xcb, 0x27, 0xee, 0x1e, 0xa9, 0x41, 0x92,
	0xa5, 0x9c, 0x11, 0xce, 0x13, 0x57, 0x66, 0x7e, 0x69, 0x99, 0xe7, 0x86, 0xb8, 0x37, 0xe3, 0x5d,
	0xa4, 0x9c, 0x9d, 0xf1, 0xe4, 0xc6, 0xe5, 0xaa, 0x7e, 0xf3, 0x72, 0x55, 0x70, 0xee, 0x1d, 0x39,
	0xf2, 0xe3, 0x42, 0x88, 0x3f, 0x81, 0xf5, 0xb9, 0x10, 0xd7, 0x45, 0x2a, 0x4f, 0x98, 0x0a, 0x46,
	0xc5, 0xf8, 0xf6, 0xd2, 0xcb, 0x1f, 0xe8, 0x44, 0xbb, 0xdf, 0x74, 0xf5, 0x8c, 0x91, 0x4b, 0x8f,
	0x05, 0xb1, 0xbe, 0x9b, 0x6b, 0xf7, 0xbb, 0xa1, 0x5f, 0x77, 0xf3, 0x8c, 0xbd, 0xb4, 0x88, 0x76,
	0x7f, 0x17, 0x03, 0xcc, 0x4e, 0x1b, 0xb5, 0xa0, 0xfe, 0xfa, 0x8c, 0x9c, 0xe3, 0xbd, 0xde, 0x61,
	0xfb, 0x3d, 0x84, 0x60, 0x65, 0x78, 0xd6, 0x3f, 0xff, 0xdd, 0x1e, 0x3e, 0x74, 0xb2, 0x92, 0x96,
	0xbd, 0xdc, 0xc3, 0x07, 0x05, 0x59, 0x19, 0xad, 0x00, 0xf4, 0x2f, 0x4e, 0x4e, 0xdc, 0x7b, 0xe5,
	0x55, 0xb5, 0x5e, 0x6d, 0xd7, 0xba, 0xff, 0x2c, 0x41, 0x13, 0x67, 0xec, 0x94, 0x2a, 0x2f, 0xf0,
	0x94, 0x87, 0xbe, 0x01, 0x98, 0xfd, 0x96, 0x61, 0xb6, 0xd0, 0xdc, 0xbd, 0x5f, 0xf4, 0x91, 0x1e,
	0xb9, 0x74, 0xd5, 0x91, 0xb8, 0x21, 0xf3, 0x47, 0xf4, 0x1d, 0xc0, 0xec, 0x47, 0x15, 0xb3, 0x8d,
	0x85, 0x33, 0xd6, 0x23, 0xa6, 0xd9, 0xbe, 0x2e, 0x77, 0x0d, 0x3f, 0x7f, 0x43, 0x2f, 0xa0, 0x7d,
	0x23, 0xa0, 0x2a, 0xa6, 0x37, 0xae, 0xdf, 0x28, 0xec, 0x5a, 0x75, 0x35, 0x9d, 0x0f, 0xb0, 0xee,
	0x00, 0xda, 0xf6, 0xc4, 0x7b, 0x9c, 0x31, 0x6a, 0x7f, 0xa8, 0xf8, 0x10, 0x9a, 0xa1, 0xe0, 0x89,
	0x8b, 0x19, 0x57, 0x67, 0x40, 0x8b, 0x2c, 0x15, 0x7d, 0x00, 0x0d, 0xc5, 0x73, 0xd8, 0x4e, 0x42,
	0x75, 0xc5, 0x2d, 0xd8, 0xfd, 0x6b, 0x15, 0x56, 0x7b, 0x5e, 0x1c, 0xeb, 0x81, 0x34, 0x8f, 0x43,
	0x04, 0xd5, 0x90, 0xd2, 0xc0, 0x0c, 0x33, 0x0d, 0x6c, 0x9e, 0x75, 0x11, 0x0c, 0xa9, 0xf2, 0xf5,
	0x76, 0xb5, 0xd0, 0xbe, 0xa0, 0x07, 0xb0, 0xa4, 0x3c, 0x31, 0xa6, 0xca, 0x6c, 0xa3, 0x81, 0xdd,
	0x9b, 0x69, 0x24, 0x19, 0x9b, 0xa6, 0x41, 0xf5, 0x96, 0x46, 0x32, 0x0d, 0x3e, 0x0c, 0x62, 0x56,
	0x12, 0x8e, 0x61, 0xcd, 0xc5, 0xbe, 0x3f, 0xdd, 0x61, 0xa7, 0x66, 0x5c, 0x34, 0x77, 0x6f, 0x58,
	0xf4, 0x02, 0x6e, 0xab, 0x45, 0xbf, 0x9c, 0x41, 0x4b, 0xaf, 0x7c, 0xfa, 0x0b, 0xc0, 0x92, 0xb1,
	0xf2, 0xc5, 0xdc, 0x39, 0xcd, 0x6f, 0x7c, 0xa7, 0x4f, 0x69, 0xe0, 0x6e, 0xcd, 0x6e, 0x3c, 0x0b,
	0x67, 0x12, 0x84, 0x61, 0xd9, 0xec, 0x7a, 0x6a, 0xf1, 0x7d, 0x63, 0xf1, 0xcb, 0xbb, 0x2d, 0x2a,
	0xff, 0x72, 0xce, 0x64, 0x2b, 0x2c, 0x88, 0xf4, 0xdd, 0xdc, 0xda, 0x34, 0xa3, 0xb8, 0x9c, 0x30,
	0xdf, 0x0d, 0x05, 0xf6, 0x53, 0xc3, 0x37, 0x51, 0x3a, 0x9c, 0x30, 0x5f, 0x77, 0xaa, 0xc5, 0xc5,
	0xfd, 0x5c, 0xa7, 0x6a, 0x14, 0x3b, 0xd5, 0x0b, 0x58, 0xbb, 0xb1, 0x94, 0xff, 0xc7, 0xc0, 0xfe,
	0x97, 0xd0, 0xe1, 0x62, 0x5c, 0xdc, 0xea, 0xf4, 0xe7, 0xc0, 0xfd, 0x56, 0xa1, 0xdd, 0xca, 0x41,
	0xe9, 0x5f, 0xa5, 0xd2, 0x68, 0xc9, 0xfc, 0x32, 0xf7, 0xf5, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xfd, 0x52, 0x69, 0xd8, 0xcb, 0x14, 0x00, 0x00,
}
